sed -i '' 's/const \[showNotifications, setShowNotifications\] = useState(false);/const [showNotifications, setShowNotifications] = useState(false);\n  const [showProfile, setShowProfile] = useState(false);\n  const profileRef = useRef<HTMLDivElement>(null);/g' src/components/layout/Header.tsx

sed -i '' 's/if (notifRef.current && !notifRef.current.contains(event.target as Node)) {/if (notifRef.current && !notifRef.current.contains(event.target as Node)) {\n        setShowNotifications(false);\n      }\n      if (profileRef.current && !profileRef.current.contains(event.target as Node)) {\n        setShowProfile(false);/g' src/components/layout/Header.tsx

sed -i '' 's/setShowNotifications(false);//g' src/components/layout/Header.tsx

sed -i '' 's/<div className="flex items-center space-x-2 pl-2 border-l border-gray-200 dark:border-dark-border">/<div className="relative" ref={profileRef}>\n          <div className="flex items-center space-x-2 pl-2 border-l border-gray-200 dark:border-dark-border cursor-pointer" onClick={() => setShowProfile(!showProfile)}>/g' src/components/layout/Header.tsx

sed -i '' 's/<button onClick={() => showToast('"'"'User profile options are mocked for this prototype.'"'"')} className="p-1.5 bg-gray-100 dark:bg-dark-border rounded-full text-gray-600 dark:text-gray-300">/<button className="p-1.5 bg-gray-100 dark:bg-dark-border rounded-full text-gray-600 dark:text-gray-300 pointer-events-none">/g' src/components/layout/Header.tsx

sed -i '' 's/<\/button>\n        <\/div>/\&          {showProfile && (\n            <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-dark-surface border border-gray-200 dark:border-dark-border rounded-lg shadow-lg overflow-hidden z-50 py-1">\n              <a href="#" className="block px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-dark-border">Your Profile<\/a>\n              <a href="#" className="block px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-dark-border">Settings<\/a>\n              <div className="border-t border-gray-200 dark:border-dark-border my-1"><\/div>\n              <a href="#" className="block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-dark-border">Sign out<\/a>\n            <\/div>\n          )}\n        <\/div>\n      <\/div>/g' src/components/layout/Header.tsx
