sed -i '' 's/const \[showProfile, setShowProfile\] = useState(false);/const [showProfile, setShowProfile] = useState(false);\n  const [searchQuery, setSearchQuery] = useState("");\n  const [showSearchResults, setShowSearchResults] = useState(false);\n  const searchRef = useRef<HTMLDivElement>(null);/g' src/components/layout/Header.tsx

sed -i '' 's/if (profileRef.current \&\& !profileRef.current.contains(event.target as Node)) {/if (profileRef.current \&\& !profileRef.current.contains(event.target as Node)) {\n        setShowProfile(false);\n      }\n      if (searchRef.current \&\& !searchRef.current.contains(event.target as Node)) {\n        setShowSearchResults(false);/g' src/components/layout/Header.tsx

sed -i '' 's/<div className="hidden sm:flex relative">/<div className="hidden sm:flex relative" ref={searchRef}>/g' src/components/layout/Header.tsx

sed -i '' 's/placeholder="Search..."/placeholder="Search..."\n            value={searchQuery}\n            onChange={(e) => {\n              setSearchQuery(e.target.value);\n              setShowSearchResults(e.target.value.length > 0);\n            }}\n            onFocus={() => setShowSearchResults(searchQuery.length > 0)}/g' src/components/layout/Header.tsx

sed -i '' 's/<\/div>\n        \n        <button onClick={() => setIsDark(!isDark)}/  {showSearchResults \&\& (\n            <div className="absolute top-full mt-2 w-72 bg-white dark:bg-dark-surface border border-gray-200 dark:border-dark-border rounded-lg shadow-xl z-50 overflow-hidden">\n              <div className="px-4 py-2 bg-gray-50 dark:bg-dark-background border-b border-gray-200 dark:border-dark-border text-xs font-semibold text-gray-500">\n                Search Results for "{searchQuery}"\n              <\/div>\n              <div className="py-2">\n                <div className="px-4 py-2 hover:bg-gray-50 dark:hover:bg-dark-border cursor-pointer" onClick={() => { setShowSearchResults(false); setSearchQuery(""); }}>\n                  <div className="text-sm font-medium text-blue-600 dark:text-blue-400">Entity: Metro Water Works<\/div>\n                  <div className="text-xs text-gray-500">Critical Sector Entity<\/div>\n                <\/div>\n                <div className="px-4 py-2 hover:bg-gray-50 dark:hover:bg-dark-border cursor-pointer" onClick={() => { setShowSearchResults(false); setSearchQuery(""); }}>\n                  <div className="text-sm font-medium text-blue-600 dark:text-blue-400">Finding: Inadequate Log Retention<\/div>\n                  <div className="text-xs text-gray-500">Execution Gap • High Severity<\/div>\n                <\/div>\n              <\/div>\n            <\/div>\n          )}\n        <\/div>\n        \n        <button onClick={() => setIsDark(!isDark)}/g' src/components/layout/Header.tsx
