import { useState } from 'react';
import { Card } from '@/components/common/Card';
import { Modal } from '@/components/common/Modal';
import { FileText, Download, Printer, FileSpreadsheet } from 'lucide-react';
import jsPDF from 'jspdf';

export const Reports = () => {
  const [selectedReport, setSelectedReport] = useState<string | null>(null);

  const reportTypes = [
    "CSE Supervisory Assessment",
    "Entity Comparison",
    "Execution Gap Report",
    "Findings Summary"
  ];

  const handleDownloadMock = (format: string) => {
    if (format === 'PDF') {
      const doc = new jsPDF();
      doc.setFontSize(22);
      doc.text(selectedReport || 'Report', 20, 30);
      doc.setFontSize(12);
      doc.text('Supervisory Analytics Tool for SOC Assessment', 20, 40);
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 55);
      doc.text('Classification: CONFIDENTIAL', 20, 65);
      
      doc.text('This is a prototype report generated by the system.', 20, 85);
      doc.text('In a production environment, this would contain detailed', 20, 95);
      doc.text('analytical charts, tables, and findings data.', 20, 105);
      
      doc.save(`${selectedReport?.replace(/\s+/g, '_')}.pdf`);
    } else if (format === 'CSV') {
      const csvContent = `Report Type,Generated Date,Classification\
"${selectedReport}",${new Date().toLocaleDateString()},CONFIDENTIAL\
\
Metric,Value\
Total Findings,42\
Critical Gaps,3`;
      const element = document.createElement("a");
      const file = new Blob([csvContent], {type: 'text/csv;charset=utf-8;'});
      element.href = URL.createObjectURL(file);
      element.download = `${selectedReport?.replace(/\s+/g, '_')}.csv`;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    }
    setSelectedReport(null);
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {reportTypes.map((type, i) => (
          <Card key={i} className="flex items-center justify-between p-6">
            <div className="flex items-center space-x-4">
              <div className="bg-blue-100 dark:bg-blue-900/40 p-3 rounded-lg text-blue-600 dark:text-blue-400">
                <FileText className="h-6 w-6" />
              </div>
              <div>
                <h3 className="font-medium text-gray-900 dark:text-white">{type}</h3>
                <p className="text-sm text-gray-500">Generate a comprehensive analytical report.</p>
              </div>
            </div>
            <button 
              onClick={() => setSelectedReport(type)}
              className="px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 transition-colors"
            >
              Generate
            </button>
          </Card>
        ))}
      </div>

      <Modal 
        isOpen={!!selectedReport} 
        onClose={() => setSelectedReport(null)}
        title="Report Preview"
        maxWidth="3xl"
        footer={
          <>
            <button onClick={() => setSelectedReport(null)} className="px-4 py-2 text-gray-700 bg-gray-100 hover:bg-gray-200 dark:text-gray-300 dark:bg-dark-border dark:hover:bg-gray-700 rounded-lg text-sm font-medium transition-colors">Cancel</button>
            <button onClick={() => handleDownloadMock('CSV')} className="flex items-center px-4 py-2 text-green-700 bg-green-50 border border-green-200 hover:bg-green-100 dark:bg-green-900/20 dark:text-green-400 dark:border-green-800 rounded-lg text-sm font-medium transition-colors">
              <FileSpreadsheet className="w-4 h-4 mr-2" /> Export CSV
            </button>
            <button onClick={() => handleDownloadMock('PDF')} className="flex items-center px-4 py-2 text-white bg-blue-600 hover:bg-blue-700 rounded-lg text-sm font-medium transition-colors">
              <Download className="w-4 h-4 mr-2" /> Export PDF
            </button>
          </>
        }
      >
        <div className="bg-gray-100 dark:bg-dark-background p-8 rounded-lg min-h-[400px] border border-gray-200 dark:border-dark-border flex flex-col">
          <div className="flex justify-between items-start mb-8 border-b border-gray-300 dark:border-gray-700 pb-4">
            <div>
              <h1 className="text-2xl font-bold text-gray-900 dark:text-white">{selectedReport}</h1>
              <p className="text-gray-500 mt-1">Supervisory Analytics Tool for SOC Assessment</p>
            </div>
            <div className="text-right text-sm text-gray-500">
              <p>Generated: {new Date().toLocaleDateString()}</p>
              <p>Classification: CONFIDENTIAL</p>
            </div>
          </div>
          
          <div className="space-y-4 flex-1">
            <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-3/4"></div>
            <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-full"></div>
            <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-5/6"></div>
            <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-full"></div>
            <div className="h-32 bg-gray-200 dark:bg-gray-700 rounded w-full mt-6 flex items-center justify-center text-gray-400">
              [ Analytical Chart Placeholder ]
            </div>
            <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-4/5 mt-6"></div>
            <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-full"></div>
          </div>
          
          <div className="mt-8 flex justify-center">
            <button onClick={() => window.print()} className="flex items-center text-sm text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 transition-colors">
              <Printer className="w-4 h-4 mr-2" /> Print Preview
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
};